[project]
name = "teste-agno"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=2.3.4",
    "ddgs>=9.9.2",
    "fastapi[standard]>=0.123.0",
    "openai>=2.8.1",
]
